name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby: ["2.6", "2.7"]
    steps:
    - name: Check out code
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@dffc446db9ba5a0c4446edb5bca1c5c473a806c5 # v1.235.0
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
        bundler: latest
    - name: Ruby Tests
      run: bundle exec rake test
